server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service-1
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog_1
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop-1

info:
  system: Polar Bookshop

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, flyway, info
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
