polar:
  greeting: Welcome to the book catalog from a Kubernetes development environment!
spring:
  datasource:
    url: jdbc:postgresql://polar-postgres-1:5432/polardb_catalog_1
  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://polar-keycloak-1/realms/PolarBookshop-1