apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-1
  labels:
    app: catalog-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-1
  template:
    metadata:
      labels:
        app: catalog-service-1
    spec:
      containers:
        - name: catalog-service-1
          image: catalog-service-1
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres-1:5432/polardb_catalog_1
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
